// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_dashboard.sql

package db

import (
	"context"
	"time"
)

const countPendingQueue = `-- name: CountPendingQueue :one
SELECT COUNT(*) AS pending_count
FROM review_runs
WHERE status = 'pending'
`

func (q *Queries) CountPendingQueue(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingQueue)
	var pending_count int64
	err := row.Scan(&pending_count)
	return pending_count, err
}

const countRetryScheduledRuns = `-- name: CountRetryScheduledRuns :one
SELECT COUNT(*) AS retry_scheduled_count
FROM review_runs
WHERE status = 'failed'
  AND next_retry_at IS NOT NULL
`

func (q *Queries) CountRetryScheduledRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRetryScheduledRuns)
	var retry_scheduled_count int64
	err := row.Scan(&retry_scheduled_count)
	return retry_scheduled_count, err
}

const countSupersededRunsSince = `-- name: CountSupersededRunsSince :one
SELECT COUNT(*) AS superseded_count
FROM review_runs
WHERE superseded_by_run_id IS NOT NULL
  AND updated_at >= ?
`

func (q *Queries) CountSupersededRunsSince(ctx context.Context, updatedAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSupersededRunsSince, updatedAt)
	var superseded_count int64
	err := row.Scan(&superseded_count)
	return superseded_count, err
}

const getOldestWaitingRunCreatedAt = `-- name: GetOldestWaitingRunCreatedAt :one
SELECT MIN(
           CASE
               WHEN status = 'pending' THEN created_at
               WHEN status = 'failed'
                   AND next_retry_at IS NOT NULL
                   AND next_retry_at <= CURRENT_TIMESTAMP THEN next_retry_at
               ELSE NULL
               END
       ) AS created_at
FROM review_runs
WHERE status = 'pending'
   OR (status = 'failed' AND next_retry_at IS NOT NULL)
`

func (q *Queries) GetOldestWaitingRunCreatedAt(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getOldestWaitingRunCreatedAt)
	var created_at interface{}
	err := row.Scan(&created_at)
	return created_at, err
}

const listActiveWorkersWithCapacity = `-- name: ListActiveWorkersWithCapacity :many
SELECT
    h.worker_id,
    h.hostname,
    h.version,
    h.configured_concurrency,
    h.started_at,
    h.last_seen_at,
    COUNT(r.id) AS running_runs
FROM worker_heartbeats h
LEFT JOIN review_runs r
    ON r.claimed_by = h.worker_id
   AND r.status = 'running'
WHERE h.last_seen_at >= ?
GROUP BY
    h.worker_id,
    h.hostname,
    h.version,
    h.configured_concurrency,
    h.started_at,
    h.last_seen_at
ORDER BY h.worker_id ASC
`

type ListActiveWorkersWithCapacityRow struct {
	WorkerID              string    `json:"worker_id"`
	Hostname              string    `json:"hostname"`
	Version               string    `json:"version"`
	ConfiguredConcurrency int32     `json:"configured_concurrency"`
	StartedAt             time.Time `json:"started_at"`
	LastSeenAt            time.Time `json:"last_seen_at"`
	RunningRuns           int64     `json:"running_runs"`
}

func (q *Queries) ListActiveWorkersWithCapacity(ctx context.Context, lastSeenAt time.Time) ([]ListActiveWorkersWithCapacityRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWorkersWithCapacity, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveWorkersWithCapacityRow{}
	for rows.Next() {
		var i ListActiveWorkersWithCapacityRow
		if err := rows.Scan(
			&i.WorkerID,
			&i.Hostname,
			&i.Version,
			&i.ConfiguredConcurrency,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.RunningRuns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailureCountsByErrorCode = `-- name: ListFailureCountsByErrorCode :many
SELECT
    error_code,
    COUNT(*) AS count
FROM review_runs
WHERE status = 'failed'
  AND error_code <> ''
  AND superseded_by_run_id IS NULL
  AND updated_at >= ?
GROUP BY error_code
ORDER BY count DESC, error_code ASC
`

type ListFailureCountsByErrorCodeRow struct {
	ErrorCode string `json:"error_code"`
	Count     int64  `json:"count"`
}

func (q *Queries) ListFailureCountsByErrorCode(ctx context.Context, updatedAt time.Time) ([]ListFailureCountsByErrorCodeRow, error) {
	rows, err := q.db.QueryContext(ctx, listFailureCountsByErrorCode, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailureCountsByErrorCodeRow{}
	for rows.Next() {
		var i ListFailureCountsByErrorCodeRow
		if err := rows.Scan(&i.ErrorCode, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFailedRuns = `-- name: ListRecentFailedRuns :many
SELECT
    id,
    project_id,
    merge_request_id,
    trigger_type,
    head_sha,
    error_code,
    updated_at
FROM review_runs
WHERE status = 'failed'
  AND error_code <> ''
  AND superseded_by_run_id IS NULL
ORDER BY updated_at DESC, id DESC
LIMIT ?
`

type ListRecentFailedRunsRow struct {
	ID             int64     `json:"id"`
	ProjectID      int64     `json:"project_id"`
	MergeRequestID int64     `json:"merge_request_id"`
	TriggerType    string    `json:"trigger_type"`
	HeadSha        string    `json:"head_sha"`
	ErrorCode      string    `json:"error_code"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) ListRecentFailedRuns(ctx context.Context, limit int32) ([]ListRecentFailedRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentFailedRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentFailedRunsRow{}
	for rows.Next() {
		var i ListRecentFailedRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MergeRequestID,
			&i.TriggerType,
			&i.HeadSha,
			&i.ErrorCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopQueuedProjects = `-- name: ListTopQueuedProjects :many
SELECT
    p.path_with_namespace,
    COUNT(*) AS queue_depth
FROM review_runs r
JOIN projects p ON p.id = r.project_id
WHERE r.status = 'pending'
   OR (r.status = 'failed' AND r.next_retry_at IS NOT NULL)
GROUP BY p.id, p.path_with_namespace
ORDER BY queue_depth DESC, p.path_with_namespace ASC
LIMIT ?
`

type ListTopQueuedProjectsRow struct {
	PathWithNamespace string `json:"path_with_namespace"`
	QueueDepth        int64  `json:"queue_depth"`
}

func (q *Queries) ListTopQueuedProjects(ctx context.Context, limit int32) ([]ListTopQueuedProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopQueuedProjects, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopQueuedProjectsRow{}
	for rows.Next() {
		var i ListTopQueuedProjectsRow
		if err := rows.Scan(&i.PathWithNamespace, &i.QueueDepth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookVerificationCounts = `-- name: ListWebhookVerificationCounts :many
SELECT
    verification_outcome,
    COUNT(*) AS count
FROM audit_logs
WHERE verification_outcome IN ('rejected', 'deduplicated')
  AND created_at >= ?
GROUP BY verification_outcome
ORDER BY verification_outcome ASC
`

type ListWebhookVerificationCountsRow struct {
	VerificationOutcome string `json:"verification_outcome"`
	Count               int64  `json:"count"`
}

func (q *Queries) ListWebhookVerificationCounts(ctx context.Context, createdAt time.Time) ([]ListWebhookVerificationCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookVerificationCounts, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookVerificationCountsRow{}
	for rows.Next() {
		var i ListWebhookVerificationCountsRow
		if err := rows.Scan(&i.VerificationOutcome, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
