// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const insertAuditLog = `-- name: InsertAuditLog :execresult
INSERT INTO audit_logs (
    entity_type, entity_id, action, actor, detail,
    delivery_key, hook_source, verification_outcome, rejection_reason, error_code
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	EntityType          string          `json:"entity_type"`
	EntityID            int64           `json:"entity_id"`
	Action              string          `json:"action"`
	Actor               string          `json:"actor"`
	Detail              json.RawMessage `json:"detail"`
	DeliveryKey         string          `json:"delivery_key"`
	HookSource          string          `json:"hook_source"`
	VerificationOutcome string          `json:"verification_outcome"`
	RejectionReason     string          `json:"rejection_reason"`
	ErrorCode           string          `json:"error_code"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Actor,
		arg.Detail,
		arg.DeliveryKey,
		arg.HookSource,
		arg.VerificationOutcome,
		arg.RejectionReason,
		arg.ErrorCode,
	)
}

const listAuditLogsByDeliveryKey = `-- name: ListAuditLogsByDeliveryKey :many
SELECT id, entity_type, entity_id, action, actor, detail, delivery_key, hook_source, verification_outcome, rejection_reason, error_code, created_at FROM audit_logs
WHERE delivery_key = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAuditLogsByDeliveryKey(ctx context.Context, deliveryKey string) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByDeliveryKey, deliveryKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Actor,
			&i.Detail,
			&i.DeliveryKey,
			&i.HookSource,
			&i.VerificationOutcome,
			&i.RejectionReason,
			&i.ErrorCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT id, entity_type, entity_id, action, actor, detail, delivery_key, hook_source, verification_outcome, rejection_reason, error_code, created_at FROM audit_logs
WHERE entity_type = ? AND entity_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Actor,
			&i.Detail,
			&i.DeliveryKey,
			&i.HookSource,
			&i.VerificationOutcome,
			&i.RejectionReason,
			&i.ErrorCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
