// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment_actions.sql

package db

import (
	"context"
	"database/sql"
)

const getCommentActionByIdempotencyKey = `-- name: GetCommentActionByIdempotencyKey :one
SELECT id, review_run_id, review_finding_id, action_type, idempotency_key, status, error_code, error_detail, retry_count, latency_ms, created_at, updated_at FROM comment_actions WHERE idempotency_key = ? LIMIT 1
`

func (q *Queries) GetCommentActionByIdempotencyKey(ctx context.Context, idempotencyKey string) (CommentAction, error) {
	row := q.db.QueryRowContext(ctx, getCommentActionByIdempotencyKey, idempotencyKey)
	var i CommentAction
	err := row.Scan(
		&i.ID,
		&i.ReviewRunID,
		&i.ReviewFindingID,
		&i.ActionType,
		&i.IdempotencyKey,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RetryCount,
		&i.LatencyMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCommentAction = `-- name: InsertCommentAction :execresult
INSERT INTO comment_actions (
    review_run_id, review_finding_id, action_type, idempotency_key, status
) VALUES (?, ?, ?, ?, ?)
`

type InsertCommentActionParams struct {
	ReviewRunID     int64         `json:"review_run_id"`
	ReviewFindingID sql.NullInt64 `json:"review_finding_id"`
	ActionType      string        `json:"action_type"`
	IdempotencyKey  string        `json:"idempotency_key"`
	Status          string        `json:"status"`
}

func (q *Queries) InsertCommentAction(ctx context.Context, arg InsertCommentActionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertCommentAction,
		arg.ReviewRunID,
		arg.ReviewFindingID,
		arg.ActionType,
		arg.IdempotencyKey,
		arg.Status,
	)
}

const listCommentActionsByRun = `-- name: ListCommentActionsByRun :many
SELECT id, review_run_id, review_finding_id, action_type, idempotency_key, status, error_code, error_detail, retry_count, latency_ms, created_at, updated_at FROM comment_actions
WHERE review_run_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListCommentActionsByRun(ctx context.Context, reviewRunID int64) ([]CommentAction, error) {
	rows, err := q.db.QueryContext(ctx, listCommentActionsByRun, reviewRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommentAction{}
	for rows.Next() {
		var i CommentAction
		if err := rows.Scan(
			&i.ID,
			&i.ReviewRunID,
			&i.ReviewFindingID,
			&i.ActionType,
			&i.IdempotencyKey,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.RetryCount,
			&i.LatencyMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentActionStatus = `-- name: UpdateCommentActionStatus :exec
UPDATE comment_actions
SET status = ?, error_code = ?, error_detail = ?, latency_ms = ?,
    retry_count = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCommentActionStatusParams struct {
	Status      string         `json:"status"`
	ErrorCode   string         `json:"error_code"`
	ErrorDetail sql.NullString `json:"error_detail"`
	LatencyMs   int64          `json:"latency_ms"`
	RetryCount  int32          `json:"retry_count"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateCommentActionStatus(ctx context.Context, arg UpdateCommentActionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCommentActionStatus,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.LatencyMs,
		arg.RetryCount,
		arg.ID,
	)
	return err
}
