// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gitlab_discussions.sql

package db

import (
	"context"
	"database/sql"
)

const getGitlabDiscussion = `-- name: GetGitlabDiscussion :one
SELECT id, review_finding_id, merge_request_id, gitlab_discussion_id, discussion_type, resolved, superseded_by_discussion_id, created_at, updated_at FROM gitlab_discussions WHERE id = ? LIMIT 1
`

func (q *Queries) GetGitlabDiscussion(ctx context.Context, id int64) (GitlabDiscussion, error) {
	row := q.db.QueryRowContext(ctx, getGitlabDiscussion, id)
	var i GitlabDiscussion
	err := row.Scan(
		&i.ID,
		&i.ReviewFindingID,
		&i.MergeRequestID,
		&i.GitlabDiscussionID,
		&i.DiscussionType,
		&i.Resolved,
		&i.SupersededByDiscussionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitlabDiscussionByFinding = `-- name: GetGitlabDiscussionByFinding :one
SELECT id, review_finding_id, merge_request_id, gitlab_discussion_id, discussion_type, resolved, superseded_by_discussion_id, created_at, updated_at FROM gitlab_discussions
WHERE review_finding_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetGitlabDiscussionByFinding(ctx context.Context, reviewFindingID int64) (GitlabDiscussion, error) {
	row := q.db.QueryRowContext(ctx, getGitlabDiscussionByFinding, reviewFindingID)
	var i GitlabDiscussion
	err := row.Scan(
		&i.ID,
		&i.ReviewFindingID,
		&i.MergeRequestID,
		&i.GitlabDiscussionID,
		&i.DiscussionType,
		&i.Resolved,
		&i.SupersededByDiscussionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitlabDiscussionByMergeRequestAndFinding = `-- name: GetGitlabDiscussionByMergeRequestAndFinding :one
SELECT id, review_finding_id, merge_request_id, gitlab_discussion_id, discussion_type, resolved, superseded_by_discussion_id, created_at, updated_at FROM gitlab_discussions
WHERE merge_request_id = ?
  AND review_finding_id = ?
ORDER BY created_at DESC
LIMIT 1
`

type GetGitlabDiscussionByMergeRequestAndFindingParams struct {
	MergeRequestID  int64 `json:"merge_request_id"`
	ReviewFindingID int64 `json:"review_finding_id"`
}

func (q *Queries) GetGitlabDiscussionByMergeRequestAndFinding(ctx context.Context, arg GetGitlabDiscussionByMergeRequestAndFindingParams) (GitlabDiscussion, error) {
	row := q.db.QueryRowContext(ctx, getGitlabDiscussionByMergeRequestAndFinding, arg.MergeRequestID, arg.ReviewFindingID)
	var i GitlabDiscussion
	err := row.Scan(
		&i.ID,
		&i.ReviewFindingID,
		&i.MergeRequestID,
		&i.GitlabDiscussionID,
		&i.DiscussionType,
		&i.Resolved,
		&i.SupersededByDiscussionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGitlabDiscussion = `-- name: InsertGitlabDiscussion :execresult
INSERT INTO gitlab_discussions (
    review_finding_id, merge_request_id, gitlab_discussion_id, discussion_type, resolved
) VALUES (?, ?, ?, ?, ?)
`

type InsertGitlabDiscussionParams struct {
	ReviewFindingID    int64  `json:"review_finding_id"`
	MergeRequestID     int64  `json:"merge_request_id"`
	GitlabDiscussionID string `json:"gitlab_discussion_id"`
	DiscussionType     string `json:"discussion_type"`
	Resolved           bool   `json:"resolved"`
}

func (q *Queries) InsertGitlabDiscussion(ctx context.Context, arg InsertGitlabDiscussionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertGitlabDiscussion,
		arg.ReviewFindingID,
		arg.MergeRequestID,
		arg.GitlabDiscussionID,
		arg.DiscussionType,
		arg.Resolved,
	)
}

const updateGitlabDiscussionResolved = `-- name: UpdateGitlabDiscussionResolved :exec
UPDATE gitlab_discussions
SET resolved = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateGitlabDiscussionResolvedParams struct {
	Resolved bool  `json:"resolved"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateGitlabDiscussionResolved(ctx context.Context, arg UpdateGitlabDiscussionResolvedParams) error {
	_, err := q.db.ExecContext(ctx, updateGitlabDiscussionResolved, arg.Resolved, arg.ID)
	return err
}
