// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hook_events.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getHookEventByDeliveryKey = `-- name: GetHookEventByDeliveryKey :one
SELECT id, delivery_key, hook_source, event_type, gitlab_instance_id, project_id, mr_iid, action, head_sha, payload, verification_outcome, rejection_reason, received_at FROM hook_events WHERE delivery_key = ? LIMIT 1
`

func (q *Queries) GetHookEventByDeliveryKey(ctx context.Context, deliveryKey string) (HookEvent, error) {
	row := q.db.QueryRowContext(ctx, getHookEventByDeliveryKey, deliveryKey)
	var i HookEvent
	err := row.Scan(
		&i.ID,
		&i.DeliveryKey,
		&i.HookSource,
		&i.EventType,
		&i.GitlabInstanceID,
		&i.ProjectID,
		&i.MrIid,
		&i.Action,
		&i.HeadSha,
		&i.Payload,
		&i.VerificationOutcome,
		&i.RejectionReason,
		&i.ReceivedAt,
	)
	return i, err
}

const insertHookEvent = `-- name: InsertHookEvent :execresult
INSERT INTO hook_events (
    delivery_key, hook_source, event_type, gitlab_instance_id, project_id,
    mr_iid, action, head_sha, payload, verification_outcome, rejection_reason
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertHookEventParams struct {
	DeliveryKey         string          `json:"delivery_key"`
	HookSource          string          `json:"hook_source"`
	EventType           string          `json:"event_type"`
	GitlabInstanceID    sql.NullInt64   `json:"gitlab_instance_id"`
	ProjectID           sql.NullInt64   `json:"project_id"`
	MrIid               sql.NullInt64   `json:"mr_iid"`
	Action              string          `json:"action"`
	HeadSha             string          `json:"head_sha"`
	Payload             json.RawMessage `json:"payload"`
	VerificationOutcome string          `json:"verification_outcome"`
	RejectionReason     string          `json:"rejection_reason"`
}

func (q *Queries) InsertHookEvent(ctx context.Context, arg InsertHookEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertHookEvent,
		arg.DeliveryKey,
		arg.HookSource,
		arg.EventType,
		arg.GitlabInstanceID,
		arg.ProjectID,
		arg.MrIid,
		arg.Action,
		arg.HeadSha,
		arg.Payload,
		arg.VerificationOutcome,
		arg.RejectionReason,
	)
}

const listHookEventsByProjectMR = `-- name: ListHookEventsByProjectMR :many
SELECT id, delivery_key, hook_source, event_type, gitlab_instance_id, project_id, mr_iid, action, head_sha, payload, verification_outcome, rejection_reason, received_at FROM hook_events
WHERE project_id = ? AND mr_iid = ?
ORDER BY received_at DESC
LIMIT ? OFFSET ?
`

type ListHookEventsByProjectMRParams struct {
	ProjectID sql.NullInt64 `json:"project_id"`
	MrIid     sql.NullInt64 `json:"mr_iid"`
	Limit     int32         `json:"limit"`
	Offset    int32         `json:"offset"`
}

func (q *Queries) ListHookEventsByProjectMR(ctx context.Context, arg ListHookEventsByProjectMRParams) ([]HookEvent, error) {
	rows, err := q.db.QueryContext(ctx, listHookEventsByProjectMR,
		arg.ProjectID,
		arg.MrIid,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HookEvent{}
	for rows.Next() {
		var i HookEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryKey,
			&i.HookSource,
			&i.EventType,
			&i.GitlabInstanceID,
			&i.ProjectID,
			&i.MrIid,
			&i.Action,
			&i.HeadSha,
			&i.Payload,
			&i.VerificationOutcome,
			&i.RejectionReason,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
