// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merge_requests.sql

package db

import (
	"context"
	"database/sql"
)

const getLatestMRVersion = `-- name: GetLatestMRVersion :one
SELECT id, merge_request_id, gitlab_version_id, base_sha, start_sha, head_sha, patch_id_sha, created_at FROM mr_versions
WHERE merge_request_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMRVersion(ctx context.Context, mergeRequestID int64) (MrVersion, error) {
	row := q.db.QueryRowContext(ctx, getLatestMRVersion, mergeRequestID)
	var i MrVersion
	err := row.Scan(
		&i.ID,
		&i.MergeRequestID,
		&i.GitlabVersionID,
		&i.BaseSha,
		&i.StartSha,
		&i.HeadSha,
		&i.PatchIDSha,
		&i.CreatedAt,
	)
	return i, err
}

const getMergeRequest = `-- name: GetMergeRequest :one
SELECT id, project_id, mr_iid, title, source_branch, target_branch, author, state, is_draft, head_sha, web_url, created_at, updated_at FROM merge_requests WHERE id = ? LIMIT 1
`

func (q *Queries) GetMergeRequest(ctx context.Context, id int64) (MergeRequest, error) {
	row := q.db.QueryRowContext(ctx, getMergeRequest, id)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MrIid,
		&i.Title,
		&i.SourceBranch,
		&i.TargetBranch,
		&i.Author,
		&i.State,
		&i.IsDraft,
		&i.HeadSha,
		&i.WebUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMergeRequestByProjectMR = `-- name: GetMergeRequestByProjectMR :one
SELECT id, project_id, mr_iid, title, source_branch, target_branch, author, state, is_draft, head_sha, web_url, created_at, updated_at FROM merge_requests
WHERE project_id = ? AND mr_iid = ?
LIMIT 1
`

type GetMergeRequestByProjectMRParams struct {
	ProjectID int64 `json:"project_id"`
	MrIid     int64 `json:"mr_iid"`
}

func (q *Queries) GetMergeRequestByProjectMR(ctx context.Context, arg GetMergeRequestByProjectMRParams) (MergeRequest, error) {
	row := q.db.QueryRowContext(ctx, getMergeRequestByProjectMR, arg.ProjectID, arg.MrIid)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MrIid,
		&i.Title,
		&i.SourceBranch,
		&i.TargetBranch,
		&i.Author,
		&i.State,
		&i.IsDraft,
		&i.HeadSha,
		&i.WebUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMRVersion = `-- name: InsertMRVersion :execresult
INSERT INTO mr_versions (
    merge_request_id, gitlab_version_id, base_sha, start_sha, head_sha, patch_id_sha
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertMRVersionParams struct {
	MergeRequestID  int64  `json:"merge_request_id"`
	GitlabVersionID int64  `json:"gitlab_version_id"`
	BaseSha         string `json:"base_sha"`
	StartSha        string `json:"start_sha"`
	HeadSha         string `json:"head_sha"`
	PatchIDSha      string `json:"patch_id_sha"`
}

func (q *Queries) InsertMRVersion(ctx context.Context, arg InsertMRVersionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertMRVersion,
		arg.MergeRequestID,
		arg.GitlabVersionID,
		arg.BaseSha,
		arg.StartSha,
		arg.HeadSha,
		arg.PatchIDSha,
	)
}

const insertMergeRequest = `-- name: InsertMergeRequest :execresult
INSERT INTO merge_requests (
    project_id, mr_iid, title, source_branch, target_branch,
    author, state, is_draft, head_sha, web_url
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMergeRequestParams struct {
	ProjectID    int64  `json:"project_id"`
	MrIid        int64  `json:"mr_iid"`
	Title        string `json:"title"`
	SourceBranch string `json:"source_branch"`
	TargetBranch string `json:"target_branch"`
	Author       string `json:"author"`
	State        string `json:"state"`
	IsDraft      bool   `json:"is_draft"`
	HeadSha      string `json:"head_sha"`
	WebUrl       string `json:"web_url"`
}

func (q *Queries) InsertMergeRequest(ctx context.Context, arg InsertMergeRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertMergeRequest,
		arg.ProjectID,
		arg.MrIid,
		arg.Title,
		arg.SourceBranch,
		arg.TargetBranch,
		arg.Author,
		arg.State,
		arg.IsDraft,
		arg.HeadSha,
		arg.WebUrl,
	)
}

const updateMergeRequestState = `-- name: UpdateMergeRequestState :exec
UPDATE merge_requests
SET state = ?, head_sha = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateMergeRequestStateParams struct {
	State   string `json:"state"`
	HeadSha string `json:"head_sha"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateMergeRequestState(ctx context.Context, arg UpdateMergeRequestStateParams) error {
	_, err := q.db.ExecContext(ctx, updateMergeRequestState, arg.State, arg.HeadSha, arg.ID)
	return err
}

const upsertMergeRequest = `-- name: UpsertMergeRequest :execresult
INSERT INTO merge_requests (
    project_id, mr_iid, title, source_branch, target_branch,
    author, state, is_draft, head_sha, web_url
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    source_branch = VALUES(source_branch),
    target_branch = VALUES(target_branch),
    author = VALUES(author),
    state = VALUES(state),
    is_draft = VALUES(is_draft),
    head_sha = VALUES(head_sha),
    web_url = VALUES(web_url),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertMergeRequestParams struct {
	ProjectID    int64  `json:"project_id"`
	MrIid        int64  `json:"mr_iid"`
	Title        string `json:"title"`
	SourceBranch string `json:"source_branch"`
	TargetBranch string `json:"target_branch"`
	Author       string `json:"author"`
	State        string `json:"state"`
	IsDraft      bool   `json:"is_draft"`
	HeadSha      string `json:"head_sha"`
	WebUrl       string `json:"web_url"`
}

func (q *Queries) UpsertMergeRequest(ctx context.Context, arg UpsertMergeRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertMergeRequest,
		arg.ProjectID,
		arg.MrIid,
		arg.Title,
		arg.SourceBranch,
		arg.TargetBranch,
		arg.Author,
		arg.State,
		arg.IsDraft,
		arg.HeadSha,
		arg.WebUrl,
	)
}
