// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AuditLog struct {
	ID                  int64           `json:"id"`
	EntityType          string          `json:"entity_type"`
	EntityID            int64           `json:"entity_id"`
	Action              string          `json:"action"`
	Actor               string          `json:"actor"`
	Detail              json.RawMessage `json:"detail"`
	DeliveryKey         string          `json:"delivery_key"`
	HookSource          string          `json:"hook_source"`
	VerificationOutcome string          `json:"verification_outcome"`
	RejectionReason     string          `json:"rejection_reason"`
	ErrorCode           string          `json:"error_code"`
	CreatedAt           time.Time       `json:"created_at"`
}

type CommentAction struct {
	ID              int64          `json:"id"`
	ReviewRunID     int64          `json:"review_run_id"`
	ReviewFindingID sql.NullInt64  `json:"review_finding_id"`
	ActionType      string         `json:"action_type"`
	IdempotencyKey  string         `json:"idempotency_key"`
	Status          string         `json:"status"`
	ErrorCode       string         `json:"error_code"`
	ErrorDetail     sql.NullString `json:"error_detail"`
	RetryCount      int32          `json:"retry_count"`
	LatencyMs       int64          `json:"latency_ms"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type GitlabDiscussion struct {
	ID                       int64         `json:"id"`
	ReviewFindingID          int64         `json:"review_finding_id"`
	MergeRequestID           int64         `json:"merge_request_id"`
	GitlabDiscussionID       string        `json:"gitlab_discussion_id"`
	DiscussionType           string        `json:"discussion_type"`
	Resolved                 bool          `json:"resolved"`
	SupersededByDiscussionID sql.NullInt64 `json:"superseded_by_discussion_id"`
	CreatedAt                time.Time     `json:"created_at"`
	UpdatedAt                time.Time     `json:"updated_at"`
}

type GitlabInstance struct {
	ID        int64     `json:"id"`
	Url       string    `json:"url"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type HookEvent struct {
	ID                  int64           `json:"id"`
	DeliveryKey         string          `json:"delivery_key"`
	HookSource          string          `json:"hook_source"`
	EventType           string          `json:"event_type"`
	GitlabInstanceID    sql.NullInt64   `json:"gitlab_instance_id"`
	ProjectID           sql.NullInt64   `json:"project_id"`
	MrIid               sql.NullInt64   `json:"mr_iid"`
	Action              string          `json:"action"`
	HeadSha             string          `json:"head_sha"`
	Payload             json.RawMessage `json:"payload"`
	VerificationOutcome string          `json:"verification_outcome"`
	RejectionReason     string          `json:"rejection_reason"`
	ReceivedAt          time.Time       `json:"received_at"`
}

type MergeRequest struct {
	ID           int64     `json:"id"`
	ProjectID    int64     `json:"project_id"`
	MrIid        int64     `json:"mr_iid"`
	Title        string    `json:"title"`
	SourceBranch string    `json:"source_branch"`
	TargetBranch string    `json:"target_branch"`
	Author       string    `json:"author"`
	State        string    `json:"state"`
	IsDraft      bool      `json:"is_draft"`
	HeadSha      string    `json:"head_sha"`
	WebUrl       string    `json:"web_url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type MrVersion struct {
	ID              int64     `json:"id"`
	MergeRequestID  int64     `json:"merge_request_id"`
	GitlabVersionID int64     `json:"gitlab_version_id"`
	BaseSha         string    `json:"base_sha"`
	StartSha        string    `json:"start_sha"`
	HeadSha         string    `json:"head_sha"`
	PatchIDSha      string    `json:"patch_id_sha"`
	CreatedAt       time.Time `json:"created_at"`
}

type Project struct {
	ID                int64     `json:"id"`
	GitlabInstanceID  int64     `json:"gitlab_instance_id"`
	GitlabProjectID   int64     `json:"gitlab_project_id"`
	PathWithNamespace string    `json:"path_with_namespace"`
	Enabled           bool      `json:"enabled"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type ProjectPolicy struct {
	ID                  int64           `json:"id"`
	ProjectID           int64           `json:"project_id"`
	ConfidenceThreshold float64         `json:"confidence_threshold"`
	SeverityThreshold   string          `json:"severity_threshold"`
	IncludePaths        json.RawMessage `json:"include_paths"`
	ExcludePaths        json.RawMessage `json:"exclude_paths"`
	GateMode            string          `json:"gate_mode"`
	ProviderRoute       string          `json:"provider_route"`
	Extra               json.RawMessage `json:"extra"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

type ReviewFinding struct {
	ID                  int64          `json:"id"`
	ReviewRunID         int64          `json:"review_run_id"`
	MergeRequestID      int64          `json:"merge_request_id"`
	Category            string         `json:"category"`
	Severity            string         `json:"severity"`
	Confidence          float64        `json:"confidence"`
	Title               string         `json:"title"`
	BodyMarkdown        sql.NullString `json:"body_markdown"`
	Path                string         `json:"path"`
	AnchorKind          string         `json:"anchor_kind"`
	OldLine             sql.NullInt32  `json:"old_line"`
	NewLine             sql.NullInt32  `json:"new_line"`
	AnchorSnippet       sql.NullString `json:"anchor_snippet"`
	Evidence            sql.NullString `json:"evidence"`
	SuggestedPatch      sql.NullString `json:"suggested_patch"`
	CanonicalKey        string         `json:"canonical_key"`
	AnchorFingerprint   string         `json:"anchor_fingerprint"`
	SemanticFingerprint string         `json:"semantic_fingerprint"`
	State               string         `json:"state"`
	MatchedFindingID    sql.NullInt64  `json:"matched_finding_id"`
	LastSeenRunID       sql.NullInt64  `json:"last_seen_run_id"`
	GitlabDiscussionID  string         `json:"gitlab_discussion_id"`
	ErrorCode           string         `json:"error_code"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type ReviewRun struct {
	ID                  int64          `json:"id"`
	ProjectID           int64          `json:"project_id"`
	MergeRequestID      int64          `json:"merge_request_id"`
	HookEventID         sql.NullInt64  `json:"hook_event_id"`
	TriggerType         string         `json:"trigger_type"`
	HeadSha             string         `json:"head_sha"`
	Status              string         `json:"status"`
	ErrorCode           string         `json:"error_code"`
	ErrorDetail         sql.NullString `json:"error_detail"`
	RetryCount          int32          `json:"retry_count"`
	MaxRetries          int32          `json:"max_retries"`
	NextRetryAt         sql.NullTime   `json:"next_retry_at"`
	ClaimedBy           string         `json:"claimed_by"`
	ClaimedAt           sql.NullTime   `json:"claimed_at"`
	StartedAt           sql.NullTime   `json:"started_at"`
	CompletedAt         sql.NullTime   `json:"completed_at"`
	ProviderLatencyMs   int64          `json:"provider_latency_ms"`
	ProviderTokensTotal int64          `json:"provider_tokens_total"`
	IdempotencyKey      string         `json:"idempotency_key"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}
