// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getGitlabInstance = `-- name: GetGitlabInstance :one
SELECT id, url, name, created_at, updated_at FROM gitlab_instances WHERE id = ? LIMIT 1
`

func (q *Queries) GetGitlabInstance(ctx context.Context, id int64) (GitlabInstance, error) {
	row := q.db.QueryRowContext(ctx, getGitlabInstance, id)
	var i GitlabInstance
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitlabInstanceByURL = `-- name: GetGitlabInstanceByURL :one
SELECT id, url, name, created_at, updated_at FROM gitlab_instances WHERE url = ? LIMIT 1
`

func (q *Queries) GetGitlabInstanceByURL(ctx context.Context, url string) (GitlabInstance, error) {
	row := q.db.QueryRowContext(ctx, getGitlabInstanceByURL, url)
	var i GitlabInstance
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, gitlab_instance_id, gitlab_project_id, path_with_namespace, enabled, created_at, updated_at FROM projects WHERE id = ? LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GitlabInstanceID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByGitlabID = `-- name: GetProjectByGitlabID :one
SELECT id, gitlab_instance_id, gitlab_project_id, path_with_namespace, enabled, created_at, updated_at FROM projects
WHERE gitlab_instance_id = ? AND gitlab_project_id = ?
LIMIT 1
`

type GetProjectByGitlabIDParams struct {
	GitlabInstanceID int64 `json:"gitlab_instance_id"`
	GitlabProjectID  int64 `json:"gitlab_project_id"`
}

func (q *Queries) GetProjectByGitlabID(ctx context.Context, arg GetProjectByGitlabIDParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByGitlabID, arg.GitlabInstanceID, arg.GitlabProjectID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GitlabInstanceID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectPolicy = `-- name: GetProjectPolicy :one
SELECT id, project_id, confidence_threshold, severity_threshold, include_paths, exclude_paths, gate_mode, provider_route, extra, created_at, updated_at FROM project_policies WHERE project_id = ? LIMIT 1
`

func (q *Queries) GetProjectPolicy(ctx context.Context, projectID int64) (ProjectPolicy, error) {
	row := q.db.QueryRowContext(ctx, getProjectPolicy, projectID)
	var i ProjectPolicy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConfidenceThreshold,
		&i.SeverityThreshold,
		&i.IncludePaths,
		&i.ExcludePaths,
		&i.GateMode,
		&i.ProviderRoute,
		&i.Extra,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGitlabInstance = `-- name: InsertGitlabInstance :execresult
INSERT INTO gitlab_instances (url, name) VALUES (?, ?)
`

type InsertGitlabInstanceParams struct {
	Url  string `json:"url"`
	Name string `json:"name"`
}

func (q *Queries) InsertGitlabInstance(ctx context.Context, arg InsertGitlabInstanceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertGitlabInstance, arg.Url, arg.Name)
}

const insertProject = `-- name: InsertProject :execresult
INSERT INTO projects (gitlab_instance_id, gitlab_project_id, path_with_namespace, enabled)
VALUES (?, ?, ?, ?)
`

type InsertProjectParams struct {
	GitlabInstanceID  int64  `json:"gitlab_instance_id"`
	GitlabProjectID   int64  `json:"gitlab_project_id"`
	PathWithNamespace string `json:"path_with_namespace"`
	Enabled           bool   `json:"enabled"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertProject,
		arg.GitlabInstanceID,
		arg.GitlabProjectID,
		arg.PathWithNamespace,
		arg.Enabled,
	)
}

const insertProjectPolicy = `-- name: InsertProjectPolicy :execresult
INSERT INTO project_policies (
    project_id, confidence_threshold, severity_threshold,
    include_paths, exclude_paths, gate_mode, provider_route, extra
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProjectPolicyParams struct {
	ProjectID           int64           `json:"project_id"`
	ConfidenceThreshold float64         `json:"confidence_threshold"`
	SeverityThreshold   string          `json:"severity_threshold"`
	IncludePaths        json.RawMessage `json:"include_paths"`
	ExcludePaths        json.RawMessage `json:"exclude_paths"`
	GateMode            string          `json:"gate_mode"`
	ProviderRoute       string          `json:"provider_route"`
	Extra               json.RawMessage `json:"extra"`
}

func (q *Queries) InsertProjectPolicy(ctx context.Context, arg InsertProjectPolicyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertProjectPolicy,
		arg.ProjectID,
		arg.ConfidenceThreshold,
		arg.SeverityThreshold,
		arg.IncludePaths,
		arg.ExcludePaths,
		arg.GateMode,
		arg.ProviderRoute,
		arg.Extra,
	)
}
