// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	CancelPendingRunsForMR(ctx context.Context, mergeRequestID int64) error
	ClaimReviewRun(ctx context.Context, arg ClaimReviewRunParams) error
	CountPendingQueue(ctx context.Context) (int64, error)
	CountRetryScheduledRuns(ctx context.Context) (int64, error)
	CountSupersededRunsSince(ctx context.Context, updatedAt time.Time) (int64, error)
	GetCommentActionByIdempotencyKey(ctx context.Context, idempotencyKey string) (CommentAction, error)
	GetFindingByMRAndDiscussionID(ctx context.Context, arg GetFindingByMRAndDiscussionIDParams) (ReviewFinding, error)
	GetGitlabDiscussion(ctx context.Context, id int64) (GitlabDiscussion, error)
	GetGitlabDiscussionByFinding(ctx context.Context, reviewFindingID int64) (GitlabDiscussion, error)
	GetGitlabDiscussionByMergeRequestAndFinding(ctx context.Context, arg GetGitlabDiscussionByMergeRequestAndFindingParams) (GitlabDiscussion, error)
	GetGitlabInstance(ctx context.Context, id int64) (GitlabInstance, error)
	GetGitlabInstanceByURL(ctx context.Context, url string) (GitlabInstance, error)
	GetHookEventByDeliveryKey(ctx context.Context, deliveryKey string) (HookEvent, error)
	GetLatestMRVersion(ctx context.Context, mergeRequestID int64) (MrVersion, error)
	GetMergeRequest(ctx context.Context, id int64) (MergeRequest, error)
	GetMergeRequestByProjectMR(ctx context.Context, arg GetMergeRequestByProjectMRParams) (MergeRequest, error)
	GetNextClaimableReviewRun(ctx context.Context) (ReviewRun, error)
	GetOldestWaitingRunCreatedAt(ctx context.Context) (interface{}, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectByGitlabID(ctx context.Context, arg GetProjectByGitlabIDParams) (Project, error)
	GetProjectPolicy(ctx context.Context, projectID int64) (ProjectPolicy, error)
	GetReviewFinding(ctx context.Context, id int64) (ReviewFinding, error)
	GetReviewRun(ctx context.Context, id int64) (ReviewRun, error)
	GetReviewRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (ReviewRun, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (sql.Result, error)
	InsertCommentAction(ctx context.Context, arg InsertCommentActionParams) (sql.Result, error)
	InsertGitlabDiscussion(ctx context.Context, arg InsertGitlabDiscussionParams) (sql.Result, error)
	InsertGitlabInstance(ctx context.Context, arg InsertGitlabInstanceParams) (sql.Result, error)
	InsertHookEvent(ctx context.Context, arg InsertHookEventParams) (sql.Result, error)
	InsertMRVersion(ctx context.Context, arg InsertMRVersionParams) (sql.Result, error)
	InsertMergeRequest(ctx context.Context, arg InsertMergeRequestParams) (sql.Result, error)
	InsertProject(ctx context.Context, arg InsertProjectParams) (sql.Result, error)
	InsertProjectPolicy(ctx context.Context, arg InsertProjectPolicyParams) (sql.Result, error)
	InsertReviewFinding(ctx context.Context, arg InsertReviewFindingParams) (sql.Result, error)
	InsertReviewRun(ctx context.Context, arg InsertReviewRunParams) (sql.Result, error)
	ListActiveFindingsByMR(ctx context.Context, mergeRequestID int64) ([]ReviewFinding, error)
	ListActiveWorkerHeartbeats(ctx context.Context, lastSeenAt time.Time) ([]WorkerHeartbeat, error)
	ListActiveWorkersWithCapacity(ctx context.Context, lastSeenAt time.Time) ([]ListActiveWorkersWithCapacityRow, error)
	ListAuditLogsByDeliveryKey(ctx context.Context, deliveryKey string) ([]AuditLog, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListCommentActionsByRun(ctx context.Context, reviewRunID int64) ([]CommentAction, error)
	ListFailureCountsByErrorCode(ctx context.Context, updatedAt time.Time) ([]ListFailureCountsByErrorCodeRow, error)
	ListFindingsByMergeRequest(ctx context.Context, mergeRequestID int64) ([]ReviewFinding, error)
	ListFindingsByRun(ctx context.Context, reviewRunID int64) ([]ReviewFinding, error)
	ListHookEventsByProjectMR(ctx context.Context, arg ListHookEventsByProjectMRParams) ([]HookEvent, error)
	ListPendingRuns(ctx context.Context, limit int32) ([]ReviewRun, error)
	ListRecentFailedRuns(ctx context.Context, limit int32) ([]ListRecentFailedRunsRow, error)
	ListReviewRunsByMR(ctx context.Context, mergeRequestID int64) ([]ReviewRun, error)
	ListRunningRunCountsByWorker(ctx context.Context) ([]ListRunningRunCountsByWorkerRow, error)
	ListTopQueuedProjects(ctx context.Context, limit int32) ([]ListTopQueuedProjectsRow, error)
	ListWebhookVerificationCounts(ctx context.Context, createdAt time.Time) ([]ListWebhookVerificationCountsRow, error)
	MarkReviewRunFailed(ctx context.Context, arg MarkReviewRunFailedParams) error
	MarkReviewRunRetryableFailure(ctx context.Context, arg MarkReviewRunRetryableFailureParams) error
	ReapStaleRunningRuns(ctx context.Context, dateSUB interface{}) (int64, error)
	SupersedeActiveRunsForMR(ctx context.Context, arg SupersedeActiveRunsForMRParams) error
	UpdateCommentActionStatus(ctx context.Context, arg UpdateCommentActionStatusParams) error
	UpdateFindingDiscussionID(ctx context.Context, arg UpdateFindingDiscussionIDParams) error
	UpdateFindingLastSeen(ctx context.Context, arg UpdateFindingLastSeenParams) error
	UpdateFindingRelocation(ctx context.Context, arg UpdateFindingRelocationParams) error
	UpdateFindingState(ctx context.Context, arg UpdateFindingStateParams) error
	UpdateGitlabDiscussionResolved(ctx context.Context, arg UpdateGitlabDiscussionResolvedParams) error
	UpdateGitlabDiscussionSupersededBy(ctx context.Context, arg UpdateGitlabDiscussionSupersededByParams) error
	UpdateMergeRequestState(ctx context.Context, arg UpdateMergeRequestStateParams) error
	UpdateReviewRunCompleted(ctx context.Context, arg UpdateReviewRunCompletedParams) error
	UpdateReviewRunStatus(ctx context.Context, arg UpdateReviewRunStatusParams) error
	UpdateRunScopeJSON(ctx context.Context, arg UpdateRunScopeJSONParams) error
	UpsertGitlabInstance(ctx context.Context, arg UpsertGitlabInstanceParams) (sql.Result, error)
	UpsertMergeRequest(ctx context.Context, arg UpsertMergeRequestParams) (sql.Result, error)
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (sql.Result, error)
	UpsertWorkerHeartbeat(ctx context.Context, arg UpsertWorkerHeartbeatParams) error
}

var _ Querier = (*Queries)(nil)
