// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CancelPendingRunsForMR(ctx context.Context, mergeRequestID int64) error
	GetCommentActionByIdempotencyKey(ctx context.Context, idempotencyKey string) (CommentAction, error)
	GetGitlabDiscussion(ctx context.Context, id int64) (GitlabDiscussion, error)
	GetGitlabDiscussionByFinding(ctx context.Context, reviewFindingID int64) (GitlabDiscussion, error)
	GetGitlabInstance(ctx context.Context, id int64) (GitlabInstance, error)
	GetGitlabInstanceByURL(ctx context.Context, url string) (GitlabInstance, error)
	GetHookEventByDeliveryKey(ctx context.Context, deliveryKey string) (HookEvent, error)
	GetLatestMRVersion(ctx context.Context, mergeRequestID int64) (MrVersion, error)
	GetMergeRequest(ctx context.Context, id int64) (MergeRequest, error)
	GetMergeRequestByProjectMR(ctx context.Context, arg GetMergeRequestByProjectMRParams) (MergeRequest, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectByGitlabID(ctx context.Context, arg GetProjectByGitlabIDParams) (Project, error)
	GetProjectPolicy(ctx context.Context, projectID int64) (ProjectPolicy, error)
	GetReviewFinding(ctx context.Context, id int64) (ReviewFinding, error)
	GetReviewRun(ctx context.Context, id int64) (ReviewRun, error)
	GetReviewRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (ReviewRun, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (sql.Result, error)
	InsertCommentAction(ctx context.Context, arg InsertCommentActionParams) (sql.Result, error)
	InsertGitlabDiscussion(ctx context.Context, arg InsertGitlabDiscussionParams) (sql.Result, error)
	InsertGitlabInstance(ctx context.Context, arg InsertGitlabInstanceParams) (sql.Result, error)
	InsertHookEvent(ctx context.Context, arg InsertHookEventParams) (sql.Result, error)
	InsertMRVersion(ctx context.Context, arg InsertMRVersionParams) (sql.Result, error)
	InsertMergeRequest(ctx context.Context, arg InsertMergeRequestParams) (sql.Result, error)
	InsertProject(ctx context.Context, arg InsertProjectParams) (sql.Result, error)
	InsertProjectPolicy(ctx context.Context, arg InsertProjectPolicyParams) (sql.Result, error)
	InsertReviewFinding(ctx context.Context, arg InsertReviewFindingParams) (sql.Result, error)
	InsertReviewRun(ctx context.Context, arg InsertReviewRunParams) (sql.Result, error)
	ListActiveFindingsByMR(ctx context.Context, mergeRequestID int64) ([]ReviewFinding, error)
	ListAuditLogsByDeliveryKey(ctx context.Context, deliveryKey string) ([]AuditLog, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListCommentActionsByRun(ctx context.Context, reviewRunID int64) ([]CommentAction, error)
	ListFindingsByRun(ctx context.Context, reviewRunID int64) ([]ReviewFinding, error)
	ListHookEventsByProjectMR(ctx context.Context, arg ListHookEventsByProjectMRParams) ([]HookEvent, error)
	ListPendingRuns(ctx context.Context, limit int32) ([]ReviewRun, error)
	UpdateCommentActionStatus(ctx context.Context, arg UpdateCommentActionStatusParams) error
	UpdateFindingLastSeen(ctx context.Context, arg UpdateFindingLastSeenParams) error
	UpdateFindingState(ctx context.Context, arg UpdateFindingStateParams) error
	UpdateGitlabDiscussionResolved(ctx context.Context, arg UpdateGitlabDiscussionResolvedParams) error
	UpdateMergeRequestState(ctx context.Context, arg UpdateMergeRequestStateParams) error
	UpdateReviewRunCompleted(ctx context.Context, arg UpdateReviewRunCompletedParams) error
	UpdateReviewRunStatus(ctx context.Context, arg UpdateReviewRunStatusParams) error
}

var _ Querier = (*Queries)(nil)
