// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_runs.sql

package db

import (
	"context"
	"database/sql"
)

const cancelPendingRunsForMR = `-- name: CancelPendingRunsForMR :exec
UPDATE review_runs
SET status = 'cancelled', updated_at = CURRENT_TIMESTAMP
WHERE merge_request_id = ? AND status IN ('pending', 'running')
`

func (q *Queries) CancelPendingRunsForMR(ctx context.Context, mergeRequestID int64) error {
	_, err := q.db.ExecContext(ctx, cancelPendingRunsForMR, mergeRequestID)
	return err
}

const getReviewRun = `-- name: GetReviewRun :one
SELECT id, project_id, merge_request_id, hook_event_id, trigger_type, head_sha, status, error_code, error_detail, retry_count, max_retries, next_retry_at, claimed_by, claimed_at, started_at, completed_at, provider_latency_ms, provider_tokens_total, idempotency_key, created_at, updated_at FROM review_runs WHERE id = ? LIMIT 1
`

func (q *Queries) GetReviewRun(ctx context.Context, id int64) (ReviewRun, error) {
	row := q.db.QueryRowContext(ctx, getReviewRun, id)
	var i ReviewRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MergeRequestID,
		&i.HookEventID,
		&i.TriggerType,
		&i.HeadSha,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProviderLatencyMs,
		&i.ProviderTokensTotal,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewRunByIdempotencyKey = `-- name: GetReviewRunByIdempotencyKey :one
SELECT id, project_id, merge_request_id, hook_event_id, trigger_type, head_sha, status, error_code, error_detail, retry_count, max_retries, next_retry_at, claimed_by, claimed_at, started_at, completed_at, provider_latency_ms, provider_tokens_total, idempotency_key, created_at, updated_at FROM review_runs WHERE idempotency_key = ? LIMIT 1
`

func (q *Queries) GetReviewRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (ReviewRun, error) {
	row := q.db.QueryRowContext(ctx, getReviewRunByIdempotencyKey, idempotencyKey)
	var i ReviewRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MergeRequestID,
		&i.HookEventID,
		&i.TriggerType,
		&i.HeadSha,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProviderLatencyMs,
		&i.ProviderTokensTotal,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReviewRun = `-- name: InsertReviewRun :execresult
INSERT INTO review_runs (
    project_id, merge_request_id, hook_event_id, trigger_type, head_sha,
    status, max_retries, idempotency_key
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertReviewRunParams struct {
	ProjectID      int64         `json:"project_id"`
	MergeRequestID int64         `json:"merge_request_id"`
	HookEventID    sql.NullInt64 `json:"hook_event_id"`
	TriggerType    string        `json:"trigger_type"`
	HeadSha        string        `json:"head_sha"`
	Status         string        `json:"status"`
	MaxRetries     int32         `json:"max_retries"`
	IdempotencyKey string        `json:"idempotency_key"`
}

func (q *Queries) InsertReviewRun(ctx context.Context, arg InsertReviewRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertReviewRun,
		arg.ProjectID,
		arg.MergeRequestID,
		arg.HookEventID,
		arg.TriggerType,
		arg.HeadSha,
		arg.Status,
		arg.MaxRetries,
		arg.IdempotencyKey,
	)
}

const listPendingRuns = `-- name: ListPendingRuns :many
SELECT id, project_id, merge_request_id, hook_event_id, trigger_type, head_sha, status, error_code, error_detail, retry_count, max_retries, next_retry_at, claimed_by, claimed_at, started_at, completed_at, provider_latency_ms, provider_tokens_total, idempotency_key, created_at, updated_at FROM review_runs
WHERE status = 'pending' AND (next_retry_at IS NULL OR next_retry_at <= CURRENT_TIMESTAMP)
ORDER BY created_at ASC
LIMIT ?
`

func (q *Queries) ListPendingRuns(ctx context.Context, limit int32) ([]ReviewRun, error) {
	rows, err := q.db.QueryContext(ctx, listPendingRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRun{}
	for rows.Next() {
		var i ReviewRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MergeRequestID,
			&i.HookEventID,
			&i.TriggerType,
			&i.HeadSha,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ProviderLatencyMs,
			&i.ProviderTokensTotal,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewRunCompleted = `-- name: UpdateReviewRunCompleted :exec
UPDATE review_runs
SET status = 'completed', completed_at = CURRENT_TIMESTAMP,
    provider_latency_ms = ?, provider_tokens_total = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateReviewRunCompletedParams struct {
	ProviderLatencyMs   int64 `json:"provider_latency_ms"`
	ProviderTokensTotal int64 `json:"provider_tokens_total"`
	ID                  int64 `json:"id"`
}

func (q *Queries) UpdateReviewRunCompleted(ctx context.Context, arg UpdateReviewRunCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateReviewRunCompleted, arg.ProviderLatencyMs, arg.ProviderTokensTotal, arg.ID)
	return err
}

const updateReviewRunStatus = `-- name: UpdateReviewRunStatus :exec
UPDATE review_runs
SET status = ?, error_code = ?, error_detail = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateReviewRunStatusParams struct {
	Status      string         `json:"status"`
	ErrorCode   string         `json:"error_code"`
	ErrorDetail sql.NullString `json:"error_detail"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateReviewRunStatus(ctx context.Context, arg UpdateReviewRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReviewRunStatus,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.ID,
	)
	return err
}
