// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_runs.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const cancelPendingRunsForMR = `-- name: CancelPendingRunsForMR :exec
UPDATE review_runs
SET status = 'cancelled',
    next_retry_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE merge_request_id = ?
  AND (
    status IN ('pending', 'running')
    OR (status = 'failed' AND next_retry_at IS NOT NULL)
  )
`

func (q *Queries) CancelPendingRunsForMR(ctx context.Context, mergeRequestID int64) error {
	_, err := q.db.ExecContext(ctx, cancelPendingRunsForMR, mergeRequestID)
	return err
}

const claimReviewRun = `-- name: ClaimReviewRun :exec
UPDATE review_runs
SET status = 'running',
    claimed_by = ?,
    claimed_at = CURRENT_TIMESTAMP,
    started_at = COALESCE(started_at, CURRENT_TIMESTAMP),
    next_retry_at = NULL,
    error_code = '',
    error_detail = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type ClaimReviewRunParams struct {
	ClaimedBy string `json:"claimed_by"`
	ID        int64  `json:"id"`
}

func (q *Queries) ClaimReviewRun(ctx context.Context, arg ClaimReviewRunParams) error {
	_, err := q.db.ExecContext(ctx, claimReviewRun, arg.ClaimedBy, arg.ID)
	return err
}

const getNextClaimableReviewRun = `-- name: GetNextClaimableReviewRun :one
SELECT id, project_id, merge_request_id, hook_event_id, trigger_type, head_sha, status, error_code, error_detail, retry_count, max_retries, next_retry_at, claimed_by, claimed_at, started_at, completed_at, provider_latency_ms, provider_tokens_total, idempotency_key, created_at, updated_at, scope_json FROM review_runs
WHERE status = 'pending'
   OR (status = 'failed' AND next_retry_at IS NOT NULL AND next_retry_at <= CURRENT_TIMESTAMP)
ORDER BY
    CASE WHEN status = 'pending' THEN 0 ELSE 1 END,
    COALESCE(next_retry_at, created_at) ASC,
    created_at ASC,
    id ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetNextClaimableReviewRun(ctx context.Context) (ReviewRun, error) {
	row := q.db.QueryRowContext(ctx, getNextClaimableReviewRun)
	var i ReviewRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MergeRequestID,
		&i.HookEventID,
		&i.TriggerType,
		&i.HeadSha,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProviderLatencyMs,
		&i.ProviderTokensTotal,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScopeJson,
	)
	return i, err
}

const getReviewRun = `-- name: GetReviewRun :one
SELECT id, project_id, merge_request_id, hook_event_id, trigger_type, head_sha, status, error_code, error_detail, retry_count, max_retries, next_retry_at, claimed_by, claimed_at, started_at, completed_at, provider_latency_ms, provider_tokens_total, idempotency_key, created_at, updated_at, scope_json FROM review_runs WHERE id = ? LIMIT 1
`

func (q *Queries) GetReviewRun(ctx context.Context, id int64) (ReviewRun, error) {
	row := q.db.QueryRowContext(ctx, getReviewRun, id)
	var i ReviewRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MergeRequestID,
		&i.HookEventID,
		&i.TriggerType,
		&i.HeadSha,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProviderLatencyMs,
		&i.ProviderTokensTotal,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScopeJson,
	)
	return i, err
}

const getReviewRunByIdempotencyKey = `-- name: GetReviewRunByIdempotencyKey :one
SELECT id, project_id, merge_request_id, hook_event_id, trigger_type, head_sha, status, error_code, error_detail, retry_count, max_retries, next_retry_at, claimed_by, claimed_at, started_at, completed_at, provider_latency_ms, provider_tokens_total, idempotency_key, created_at, updated_at, scope_json FROM review_runs WHERE idempotency_key = ? LIMIT 1
`

func (q *Queries) GetReviewRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (ReviewRun, error) {
	row := q.db.QueryRowContext(ctx, getReviewRunByIdempotencyKey, idempotencyKey)
	var i ReviewRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MergeRequestID,
		&i.HookEventID,
		&i.TriggerType,
		&i.HeadSha,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProviderLatencyMs,
		&i.ProviderTokensTotal,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScopeJson,
	)
	return i, err
}

const insertReviewRun = `-- name: InsertReviewRun :execresult
INSERT INTO review_runs (
    project_id, merge_request_id, hook_event_id, trigger_type, head_sha,
    status, max_retries, idempotency_key, scope_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertReviewRunParams struct {
	ProjectID      int64           `json:"project_id"`
	MergeRequestID int64           `json:"merge_request_id"`
	HookEventID    sql.NullInt64   `json:"hook_event_id"`
	TriggerType    string          `json:"trigger_type"`
	HeadSha        string          `json:"head_sha"`
	Status         string          `json:"status"`
	MaxRetries     int32           `json:"max_retries"`
	IdempotencyKey string          `json:"idempotency_key"`
	ScopeJson      json.RawMessage `json:"scope_json"`
}

func (q *Queries) InsertReviewRun(ctx context.Context, arg InsertReviewRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertReviewRun,
		arg.ProjectID,
		arg.MergeRequestID,
		arg.HookEventID,
		arg.TriggerType,
		arg.HeadSha,
		arg.Status,
		arg.MaxRetries,
		arg.IdempotencyKey,
		arg.ScopeJson,
	)
}

const listPendingRuns = `-- name: ListPendingRuns :many
SELECT id, project_id, merge_request_id, hook_event_id, trigger_type, head_sha, status, error_code, error_detail, retry_count, max_retries, next_retry_at, claimed_by, claimed_at, started_at, completed_at, provider_latency_ms, provider_tokens_total, idempotency_key, created_at, updated_at, scope_json FROM review_runs
WHERE status = 'pending' AND (next_retry_at IS NULL OR next_retry_at <= CURRENT_TIMESTAMP)
ORDER BY created_at ASC
LIMIT ?
`

func (q *Queries) ListPendingRuns(ctx context.Context, limit int32) ([]ReviewRun, error) {
	rows, err := q.db.QueryContext(ctx, listPendingRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRun{}
	for rows.Next() {
		var i ReviewRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MergeRequestID,
			&i.HookEventID,
			&i.TriggerType,
			&i.HeadSha,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ProviderLatencyMs,
			&i.ProviderTokensTotal,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScopeJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewRunsByMR = `-- name: ListReviewRunsByMR :many
SELECT id, project_id, merge_request_id, hook_event_id, trigger_type, head_sha, status, error_code, error_detail, retry_count, max_retries, next_retry_at, claimed_by, claimed_at, started_at, completed_at, provider_latency_ms, provider_tokens_total, idempotency_key, created_at, updated_at, scope_json FROM review_runs
WHERE merge_request_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListReviewRunsByMR(ctx context.Context, mergeRequestID int64) ([]ReviewRun, error) {
	rows, err := q.db.QueryContext(ctx, listReviewRunsByMR, mergeRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRun{}
	for rows.Next() {
		var i ReviewRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MergeRequestID,
			&i.HookEventID,
			&i.TriggerType,
			&i.HeadSha,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ProviderLatencyMs,
			&i.ProviderTokensTotal,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScopeJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReviewRunFailed = `-- name: MarkReviewRunFailed :exec
UPDATE review_runs
SET status = 'failed',
    error_code = ?,
    error_detail = ?,
    retry_count = ?,
    next_retry_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type MarkReviewRunFailedParams struct {
	ErrorCode   string         `json:"error_code"`
	ErrorDetail sql.NullString `json:"error_detail"`
	RetryCount  int32          `json:"retry_count"`
	ID          int64          `json:"id"`
}

func (q *Queries) MarkReviewRunFailed(ctx context.Context, arg MarkReviewRunFailedParams) error {
	_, err := q.db.ExecContext(ctx, markReviewRunFailed,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.RetryCount,
		arg.ID,
	)
	return err
}

const markReviewRunRetryableFailure = `-- name: MarkReviewRunRetryableFailure :exec
UPDATE review_runs
SET status = 'failed',
    error_code = ?,
    error_detail = ?,
    retry_count = ?,
    next_retry_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type MarkReviewRunRetryableFailureParams struct {
	ErrorCode   string         `json:"error_code"`
	ErrorDetail sql.NullString `json:"error_detail"`
	RetryCount  int32          `json:"retry_count"`
	NextRetryAt sql.NullTime   `json:"next_retry_at"`
	ID          int64          `json:"id"`
}

func (q *Queries) MarkReviewRunRetryableFailure(ctx context.Context, arg MarkReviewRunRetryableFailureParams) error {
	_, err := q.db.ExecContext(ctx, markReviewRunRetryableFailure,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.RetryCount,
		arg.NextRetryAt,
		arg.ID,
	)
	return err
}

const reapStaleRunningRuns = `-- name: ReapStaleRunningRuns :execrows
UPDATE review_runs
SET status = 'failed',
    error_code = 'worker_timeout',
    error_detail = 'Run exceeded claim timeout and was reaped for retry',
    retry_count = retry_count + 1,
    next_retry_at = NOW() + INTERVAL 30 SECOND,
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'running'
  AND claimed_at < NOW() - INTERVAL ? MINUTE
`

func (q *Queries) ReapStaleRunningRuns(ctx context.Context, dateSUB interface{}) (int64, error) {
	result, err := q.db.ExecContext(ctx, reapStaleRunningRuns, dateSUB)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateReviewRunCompleted = `-- name: UpdateReviewRunCompleted :exec
UPDATE review_runs
SET status = 'completed', completed_at = CURRENT_TIMESTAMP,
    provider_latency_ms = ?, provider_tokens_total = ?,
    error_code = '', error_detail = NULL, next_retry_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateReviewRunCompletedParams struct {
	ProviderLatencyMs   int64 `json:"provider_latency_ms"`
	ProviderTokensTotal int64 `json:"provider_tokens_total"`
	ID                  int64 `json:"id"`
}

func (q *Queries) UpdateReviewRunCompleted(ctx context.Context, arg UpdateReviewRunCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateReviewRunCompleted, arg.ProviderLatencyMs, arg.ProviderTokensTotal, arg.ID)
	return err
}

const updateReviewRunStatus = `-- name: UpdateReviewRunStatus :exec
UPDATE review_runs
SET status = ?, error_code = ?, error_detail = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateReviewRunStatusParams struct {
	Status      string         `json:"status"`
	ErrorCode   string         `json:"error_code"`
	ErrorDetail sql.NullString `json:"error_detail"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateReviewRunStatus(ctx context.Context, arg UpdateReviewRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReviewRunStatus,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.ID,
	)
	return err
}

const updateRunScopeJSON = `-- name: UpdateRunScopeJSON :exec
UPDATE review_runs
SET scope_json = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateRunScopeJSONParams struct {
	ScopeJson json.RawMessage `json:"scope_json"`
	ID        int64           `json:"id"`
}

func (q *Queries) UpdateRunScopeJSON(ctx context.Context, arg UpdateRunScopeJSONParams) error {
	_, err := q.db.ExecContext(ctx, updateRunScopeJSON, arg.ScopeJson, arg.ID)
	return err
}
