// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_findings.sql

package db

import (
	"context"
	"database/sql"
)

const getFindingByMRAndDiscussionID = `-- name: GetFindingByMRAndDiscussionID :one
SELECT id, review_run_id, merge_request_id, category, severity, confidence, title, body_markdown, path, anchor_kind, old_line, new_line, anchor_snippet, evidence, suggested_patch, canonical_key, anchor_fingerprint, semantic_fingerprint, state, matched_finding_id, last_seen_run_id, gitlab_discussion_id, error_code, created_at, updated_at, range_start_kind, range_start_old_line, range_start_new_line, range_end_kind, range_end_old_line, range_end_new_line FROM review_findings
WHERE merge_request_id = ? AND gitlab_discussion_id = ?
LIMIT 1
`

type GetFindingByMRAndDiscussionIDParams struct {
	MergeRequestID     int64  `json:"merge_request_id"`
	GitlabDiscussionID string `json:"gitlab_discussion_id"`
}

func (q *Queries) GetFindingByMRAndDiscussionID(ctx context.Context, arg GetFindingByMRAndDiscussionIDParams) (ReviewFinding, error) {
	row := q.db.QueryRowContext(ctx, getFindingByMRAndDiscussionID, arg.MergeRequestID, arg.GitlabDiscussionID)
	var i ReviewFinding
	err := row.Scan(
		&i.ID,
		&i.ReviewRunID,
		&i.MergeRequestID,
		&i.Category,
		&i.Severity,
		&i.Confidence,
		&i.Title,
		&i.BodyMarkdown,
		&i.Path,
		&i.AnchorKind,
		&i.OldLine,
		&i.NewLine,
		&i.AnchorSnippet,
		&i.Evidence,
		&i.SuggestedPatch,
		&i.CanonicalKey,
		&i.AnchorFingerprint,
		&i.SemanticFingerprint,
		&i.State,
		&i.MatchedFindingID,
		&i.LastSeenRunID,
		&i.GitlabDiscussionID,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RangeStartKind,
		&i.RangeStartOldLine,
		&i.RangeStartNewLine,
		&i.RangeEndKind,
		&i.RangeEndOldLine,
		&i.RangeEndNewLine,
	)
	return i, err
}

const getReviewFinding = `-- name: GetReviewFinding :one
SELECT id, review_run_id, merge_request_id, category, severity, confidence, title, body_markdown, path, anchor_kind, old_line, new_line, anchor_snippet, evidence, suggested_patch, canonical_key, anchor_fingerprint, semantic_fingerprint, state, matched_finding_id, last_seen_run_id, gitlab_discussion_id, error_code, created_at, updated_at, range_start_kind, range_start_old_line, range_start_new_line, range_end_kind, range_end_old_line, range_end_new_line FROM review_findings WHERE id = ? LIMIT 1
`

func (q *Queries) GetReviewFinding(ctx context.Context, id int64) (ReviewFinding, error) {
	row := q.db.QueryRowContext(ctx, getReviewFinding, id)
	var i ReviewFinding
	err := row.Scan(
		&i.ID,
		&i.ReviewRunID,
		&i.MergeRequestID,
		&i.Category,
		&i.Severity,
		&i.Confidence,
		&i.Title,
		&i.BodyMarkdown,
		&i.Path,
		&i.AnchorKind,
		&i.OldLine,
		&i.NewLine,
		&i.AnchorSnippet,
		&i.Evidence,
		&i.SuggestedPatch,
		&i.CanonicalKey,
		&i.AnchorFingerprint,
		&i.SemanticFingerprint,
		&i.State,
		&i.MatchedFindingID,
		&i.LastSeenRunID,
		&i.GitlabDiscussionID,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RangeStartKind,
		&i.RangeStartOldLine,
		&i.RangeStartNewLine,
		&i.RangeEndKind,
		&i.RangeEndOldLine,
		&i.RangeEndNewLine,
	)
	return i, err
}

const insertReviewFinding = `-- name: InsertReviewFinding :execresult
INSERT INTO review_findings (
    review_run_id, merge_request_id, category, severity, confidence,
    title, body_markdown, path, anchor_kind, old_line, new_line,
    range_start_kind, range_start_old_line, range_start_new_line,
    range_end_kind, range_end_old_line, range_end_new_line,
    anchor_snippet, evidence, suggested_patch, canonical_key,
    anchor_fingerprint, semantic_fingerprint, state
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertReviewFindingParams struct {
	ReviewRunID         int64          `json:"review_run_id"`
	MergeRequestID      int64          `json:"merge_request_id"`
	Category            string         `json:"category"`
	Severity            string         `json:"severity"`
	Confidence          float64        `json:"confidence"`
	Title               string         `json:"title"`
	BodyMarkdown        sql.NullString `json:"body_markdown"`
	Path                string         `json:"path"`
	AnchorKind          string         `json:"anchor_kind"`
	OldLine             sql.NullInt32  `json:"old_line"`
	NewLine             sql.NullInt32  `json:"new_line"`
	RangeStartKind      sql.NullString `json:"range_start_kind"`
	RangeStartOldLine   sql.NullInt32  `json:"range_start_old_line"`
	RangeStartNewLine   sql.NullInt32  `json:"range_start_new_line"`
	RangeEndKind        sql.NullString `json:"range_end_kind"`
	RangeEndOldLine     sql.NullInt32  `json:"range_end_old_line"`
	RangeEndNewLine     sql.NullInt32  `json:"range_end_new_line"`
	AnchorSnippet       sql.NullString `json:"anchor_snippet"`
	Evidence            sql.NullString `json:"evidence"`
	SuggestedPatch      sql.NullString `json:"suggested_patch"`
	CanonicalKey        string         `json:"canonical_key"`
	AnchorFingerprint   string         `json:"anchor_fingerprint"`
	SemanticFingerprint string         `json:"semantic_fingerprint"`
	State               string         `json:"state"`
}

func (q *Queries) InsertReviewFinding(ctx context.Context, arg InsertReviewFindingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertReviewFinding,
		arg.ReviewRunID,
		arg.MergeRequestID,
		arg.Category,
		arg.Severity,
		arg.Confidence,
		arg.Title,
		arg.BodyMarkdown,
		arg.Path,
		arg.AnchorKind,
		arg.OldLine,
		arg.NewLine,
		arg.RangeStartKind,
		arg.RangeStartOldLine,
		arg.RangeStartNewLine,
		arg.RangeEndKind,
		arg.RangeEndOldLine,
		arg.RangeEndNewLine,
		arg.AnchorSnippet,
		arg.Evidence,
		arg.SuggestedPatch,
		arg.CanonicalKey,
		arg.AnchorFingerprint,
		arg.SemanticFingerprint,
		arg.State,
	)
}

const listActiveFindingsByMR = `-- name: ListActiveFindingsByMR :many
SELECT id, review_run_id, merge_request_id, category, severity, confidence, title, body_markdown, path, anchor_kind, old_line, new_line, anchor_snippet, evidence, suggested_patch, canonical_key, anchor_fingerprint, semantic_fingerprint, state, matched_finding_id, last_seen_run_id, gitlab_discussion_id, error_code, created_at, updated_at, range_start_kind, range_start_old_line, range_start_new_line, range_end_kind, range_end_old_line, range_end_new_line FROM review_findings
WHERE merge_request_id = ? AND state IN ('new', 'posted', 'active')
ORDER BY created_at ASC
`

func (q *Queries) ListActiveFindingsByMR(ctx context.Context, mergeRequestID int64) ([]ReviewFinding, error) {
	rows, err := q.db.QueryContext(ctx, listActiveFindingsByMR, mergeRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewFinding{}
	for rows.Next() {
		var i ReviewFinding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewRunID,
			&i.MergeRequestID,
			&i.Category,
			&i.Severity,
			&i.Confidence,
			&i.Title,
			&i.BodyMarkdown,
			&i.Path,
			&i.AnchorKind,
			&i.OldLine,
			&i.NewLine,
			&i.AnchorSnippet,
			&i.Evidence,
			&i.SuggestedPatch,
			&i.CanonicalKey,
			&i.AnchorFingerprint,
			&i.SemanticFingerprint,
			&i.State,
			&i.MatchedFindingID,
			&i.LastSeenRunID,
			&i.GitlabDiscussionID,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RangeStartKind,
			&i.RangeStartOldLine,
			&i.RangeStartNewLine,
			&i.RangeEndKind,
			&i.RangeEndOldLine,
			&i.RangeEndNewLine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByRun = `-- name: ListFindingsByRun :many
SELECT id, review_run_id, merge_request_id, category, severity, confidence, title, body_markdown, path, anchor_kind, old_line, new_line, anchor_snippet, evidence, suggested_patch, canonical_key, anchor_fingerprint, semantic_fingerprint, state, matched_finding_id, last_seen_run_id, gitlab_discussion_id, error_code, created_at, updated_at, range_start_kind, range_start_old_line, range_start_new_line, range_end_kind, range_end_old_line, range_end_new_line FROM review_findings
WHERE review_run_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListFindingsByRun(ctx context.Context, reviewRunID int64) ([]ReviewFinding, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsByRun, reviewRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewFinding{}
	for rows.Next() {
		var i ReviewFinding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewRunID,
			&i.MergeRequestID,
			&i.Category,
			&i.Severity,
			&i.Confidence,
			&i.Title,
			&i.BodyMarkdown,
			&i.Path,
			&i.AnchorKind,
			&i.OldLine,
			&i.NewLine,
			&i.AnchorSnippet,
			&i.Evidence,
			&i.SuggestedPatch,
			&i.CanonicalKey,
			&i.AnchorFingerprint,
			&i.SemanticFingerprint,
			&i.State,
			&i.MatchedFindingID,
			&i.LastSeenRunID,
			&i.GitlabDiscussionID,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RangeStartKind,
			&i.RangeStartOldLine,
			&i.RangeStartNewLine,
			&i.RangeEndKind,
			&i.RangeEndOldLine,
			&i.RangeEndNewLine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFindingDiscussionID = `-- name: UpdateFindingDiscussionID :exec
UPDATE review_findings
SET gitlab_discussion_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateFindingDiscussionIDParams struct {
	GitlabDiscussionID string `json:"gitlab_discussion_id"`
	ID                 int64  `json:"id"`
}

func (q *Queries) UpdateFindingDiscussionID(ctx context.Context, arg UpdateFindingDiscussionIDParams) error {
	_, err := q.db.ExecContext(ctx, updateFindingDiscussionID, arg.GitlabDiscussionID, arg.ID)
	return err
}

const updateFindingLastSeen = `-- name: UpdateFindingLastSeen :exec
UPDATE review_findings
SET last_seen_run_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateFindingLastSeenParams struct {
	LastSeenRunID sql.NullInt64 `json:"last_seen_run_id"`
	ID            int64         `json:"id"`
}

func (q *Queries) UpdateFindingLastSeen(ctx context.Context, arg UpdateFindingLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateFindingLastSeen, arg.LastSeenRunID, arg.ID)
	return err
}

const updateFindingRelocation = `-- name: UpdateFindingRelocation :exec
UPDATE review_findings
SET path = ?,
    anchor_kind = ?,
    old_line = ?,
    new_line = ?,
    range_start_kind = ?,
    range_start_old_line = ?,
    range_start_new_line = ?,
    range_end_kind = ?,
    range_end_old_line = ?,
    range_end_new_line = ?,
    anchor_snippet = ?,
    anchor_fingerprint = ?,
    semantic_fingerprint = ?,
    last_seen_run_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateFindingRelocationParams struct {
	Path                string         `json:"path"`
	AnchorKind          string         `json:"anchor_kind"`
	OldLine             sql.NullInt32  `json:"old_line"`
	NewLine             sql.NullInt32  `json:"new_line"`
	RangeStartKind      sql.NullString `json:"range_start_kind"`
	RangeStartOldLine   sql.NullInt32  `json:"range_start_old_line"`
	RangeStartNewLine   sql.NullInt32  `json:"range_start_new_line"`
	RangeEndKind        sql.NullString `json:"range_end_kind"`
	RangeEndOldLine     sql.NullInt32  `json:"range_end_old_line"`
	RangeEndNewLine     sql.NullInt32  `json:"range_end_new_line"`
	AnchorSnippet       sql.NullString `json:"anchor_snippet"`
	AnchorFingerprint   string         `json:"anchor_fingerprint"`
	SemanticFingerprint string         `json:"semantic_fingerprint"`
	LastSeenRunID       sql.NullInt64  `json:"last_seen_run_id"`
	ID                  int64          `json:"id"`
}

func (q *Queries) UpdateFindingRelocation(ctx context.Context, arg UpdateFindingRelocationParams) error {
	_, err := q.db.ExecContext(ctx, updateFindingRelocation,
		arg.Path,
		arg.AnchorKind,
		arg.OldLine,
		arg.NewLine,
		arg.RangeStartKind,
		arg.RangeStartOldLine,
		arg.RangeStartNewLine,
		arg.RangeEndKind,
		arg.RangeEndOldLine,
		arg.RangeEndNewLine,
		arg.AnchorSnippet,
		arg.AnchorFingerprint,
		arg.SemanticFingerprint,
		arg.LastSeenRunID,
		arg.ID,
	)
	return err
}

const updateFindingState = `-- name: UpdateFindingState :exec
UPDATE review_findings
SET state = ?, matched_finding_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateFindingStateParams struct {
	State            string        `json:"state"`
	MatchedFindingID sql.NullInt64 `json:"matched_finding_id"`
	ID               int64         `json:"id"`
}

func (q *Queries) UpdateFindingState(ctx context.Context, arg UpdateFindingStateParams) error {
	_, err := q.db.ExecContext(ctx, updateFindingState, arg.State, arg.MatchedFindingID, arg.ID)
	return err
}
