package db

import "context"

// Store extends the sqlc-generated Querier interface with custom methods
// that both MySQL and SQLite backends must implement. This is the primary
// abstraction for swapping database backends.
type Store interface {
	Querier

	// Custom methods not generated by sqlc (defined in review_runs_custom.go for MySQL).
	MarkReviewRunRetryableFailureIfRunning(ctx context.Context, arg MarkReviewRunRetryableFailureParams) (bool, error)
	MarkReviewRunFailedIfRunning(ctx context.Context, arg MarkReviewRunFailedParams) (bool, error)
	UpdateReviewRunCompletedIfRunning(ctx context.Context, arg UpdateReviewRunCompletedParams) (bool, error)
	UpdateReviewRunProviderMetrics(ctx context.Context, arg UpdateReviewRunProviderMetricsParams) error
}

// Verify that *Queries satisfies Store at compile time.
var _ Store = (*Queries)(nil)
