// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker_heartbeats.sql

package db

import (
	"context"
	"time"
)

const listActiveWorkerHeartbeats = `-- name: ListActiveWorkerHeartbeats :many
SELECT worker_id, hostname, version, configured_concurrency, started_at, last_seen_at, created_at, updated_at FROM worker_heartbeats
WHERE last_seen_at >= ?
ORDER BY last_seen_at DESC, worker_id ASC
`

func (q *Queries) ListActiveWorkerHeartbeats(ctx context.Context, lastSeenAt time.Time) ([]WorkerHeartbeat, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWorkerHeartbeats, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkerHeartbeat{}
	for rows.Next() {
		var i WorkerHeartbeat
		if err := rows.Scan(
			&i.WorkerID,
			&i.Hostname,
			&i.Version,
			&i.ConfiguredConcurrency,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningRunCountsByWorker = `-- name: ListRunningRunCountsByWorker :many
SELECT claimed_by AS worker_id, COUNT(*) AS running_runs
FROM review_runs
WHERE status = 'running'
  AND claimed_by <> ''
GROUP BY claimed_by
ORDER BY claimed_by ASC
`

type ListRunningRunCountsByWorkerRow struct {
	WorkerID    string `json:"worker_id"`
	RunningRuns int64  `json:"running_runs"`
}

func (q *Queries) ListRunningRunCountsByWorker(ctx context.Context) ([]ListRunningRunCountsByWorkerRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningRunCountsByWorker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunningRunCountsByWorkerRow{}
	for rows.Next() {
		var i ListRunningRunCountsByWorkerRow
		if err := rows.Scan(&i.WorkerID, &i.RunningRuns); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkerHeartbeat = `-- name: UpsertWorkerHeartbeat :exec
INSERT INTO worker_heartbeats (
    worker_id, hostname, version, configured_concurrency, started_at, last_seen_at
) VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    hostname = VALUES(hostname),
    version = VALUES(version),
    configured_concurrency = VALUES(configured_concurrency),
    last_seen_at = VALUES(last_seen_at),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertWorkerHeartbeatParams struct {
	WorkerID              string    `json:"worker_id"`
	Hostname              string    `json:"hostname"`
	Version               string    `json:"version"`
	ConfiguredConcurrency int32     `json:"configured_concurrency"`
	StartedAt             time.Time `json:"started_at"`
	LastSeenAt            time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertWorkerHeartbeat(ctx context.Context, arg UpsertWorkerHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkerHeartbeat,
		arg.WorkerID,
		arg.Hostname,
		arg.Version,
		arg.ConfiguredConcurrency,
		arg.StartedAt,
		arg.LastSeenAt,
	)
	return err
}
